# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    app_order_total:
        class: AppBundle\Service\OrderTotal

    app_helpers_extension:
        class: AppBundle\Twig\HelpersExtension
        arguments: ['@app_order_total']
        public: false
        tags:
            - { name: twig.extension }
